name: qmd files to other repo chapter subfolders

on:
#  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2.3.4
      - uses: GuillaumeFalourd/copy-push-files@v1
        with:
          source_files: '*.qmd'
          remote_repository: https://github.com/whowriteswho/whowriteswho
          target_branch: main
          target_dir: 'chapters/GIS/'
          access_token: ${{ secrets.ACCESS_TOKEN }}

#      - name: Push generated webpage to another repository
#        uses: nkoppel/push-files-to-another-repository@v1.1.0
#        env:
#          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#        with:
#          source-files: '*.qmd'
#          destination-username: 'whowriteswho'
#          destination-repository: 'chapters'
#          destination-branch: 'main'
#          destination-directory: 'GIS'
#          commit-username: 'sbalci'
#          commit-email: 'drserdarbalci@gmail.com'
